#!/bin/bash

function createFactory() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/factory.supplychain.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/factory.supplychain.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-factory --tls.certfiles "${PWD}/organizations/fabric-ca/factory/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-factory.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-factory.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-factory.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-factory.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/factory.supplychain.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy factory's CA cert to factory's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/factory.supplychain.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/factory/ca-cert.pem" "${PWD}/organizations/peerOrganizations/factory.supplychain.com/msp/tlscacerts/ca.crt"

  # Copy factory's CA cert to factory's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/factory.supplychain.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/factory/ca-cert.pem" "${PWD}/organizations/peerOrganizations/factory.supplychain.com/tlsca/tlsca.factory.supplychain.com-cert.pem"

  # Copy factory's CA cert to factory's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/factory.supplychain.com/ca"
  cp "${PWD}/organizations/fabric-ca/factory/ca-cert.pem" "${PWD}/organizations/peerOrganizations/factory.supplychain.com/ca/ca.factory.supplychain.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-factory --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/factory/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-factory --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/factory/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-factory --id.name factoryadmin --id.secret factoryadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/factory/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-factory -M "${PWD}/organizations/peerOrganizations/factory.supplychain.com/peers/peer0.factory.supplychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/factory/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/factory.supplychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/factory.supplychain.com/peers/peer0.factory.supplychain.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-factory -M "${PWD}/organizations/peerOrganizations/factory.supplychain.com/peers/peer0.factory.supplychain.com/tls" --enrollment.profile tls --csr.hosts peer0.factory.supplychain.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/factory/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/factory.supplychain.com/peers/peer0.factory.supplychain.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/factory.supplychain.com/peers/peer0.factory.supplychain.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/factory.supplychain.com/peers/peer0.factory.supplychain.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/factory.supplychain.com/peers/peer0.factory.supplychain.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/factory.supplychain.com/peers/peer0.factory.supplychain.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/factory.supplychain.com/peers/peer0.factory.supplychain.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-factory -M "${PWD}/organizations/peerOrganizations/factory.supplychain.com/users/User1@factory.supplychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/factory/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/factory.supplychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/factory.supplychain.com/users/User1@factory.supplychain.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://factoryadmin:factoryadminpw@localhost:7054 --caname ca-factory -M "${PWD}/organizations/peerOrganizations/factory.supplychain.com/users/Admin@factory.supplychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/factory/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/factory.supplychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/factory.supplychain.com/users/Admin@factory.supplychain.com/msp/config.yaml"
}

function createLogistics() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/logistics.supplychain.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/logistics.supplychain.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-logistics --tls.certfiles "${PWD}/organizations/fabric-ca/logistics/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-logistics.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-logistics.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-logistics.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-logistics.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy logistics's CA cert to logistics's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/logistics/ca-cert.pem" "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/msp/tlscacerts/ca.crt"

  # Copy logistics's CA cert to logistics's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/logistics/ca-cert.pem" "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/tlsca/tlsca.logistics.supplychain.com-cert.pem"

  # Copy logistics's CA cert to logistics's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/ca"
  cp "${PWD}/organizations/fabric-ca/logistics/ca-cert.pem" "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/ca/ca.logistics.supplychain.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-logistics --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/logistics/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-logistics --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/logistics/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-logistics --id.name logisticsadmin --id.secret logisticsadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/logistics/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-logistics -M "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/peers/peer0.logistics.supplychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/logistics/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/peers/peer0.logistics.supplychain.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-logistics -M "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/peers/peer0.logistics.supplychain.com/tls" --enrollment.profile tls --csr.hosts peer0.logistics.supplychain.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/logistics/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/peers/peer0.logistics.supplychain.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/peers/peer0.logistics.supplychain.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/peers/peer0.logistics.supplychain.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/peers/peer0.logistics.supplychain.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/peers/peer0.logistics.supplychain.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/peers/peer0.logistics.supplychain.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-logistics -M "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/users/User1@logistics.supplychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/logistics/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/users/User1@logistics.supplychain.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://logisticsadmin:logisticsadminpw@localhost:8054 --caname ca-logistics -M "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/users/Admin@logistics.supplychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/logistics/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/logistics.supplychain.com/users/Admin@logistics.supplychain.com/msp/config.yaml"
}

function createDepot() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/depot.supplychain.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/depot.supplychain.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-depot --tls.certfiles "${PWD}/organizations/fabric-ca/depot/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-depot.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-depot.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-depot.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-depot.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/depot.supplychain.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy depot's CA cert to depot's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/depot.supplychain.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/depot/ca-cert.pem" "${PWD}/organizations/peerOrganizations/depot.supplychain.com/msp/tlscacerts/ca.crt"

  # Copy depot's CA cert to depot's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/depot.supplychain.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/depot/ca-cert.pem" "${PWD}/organizations/peerOrganizations/depot.supplychain.com/tlsca/tlsca.depot.supplychain.com-cert.pem"

  # Copy depot's CA cert to depot's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/depot.supplychain.com/ca"
  cp "${PWD}/organizations/fabric-ca/depot/ca-cert.pem" "${PWD}/organizations/peerOrganizations/depot.supplychain.com/ca/ca.depot.supplychain.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-depot --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/depot/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-depot --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/depot/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-depot --id.name depotadmin --id.secret depotadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/depot/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-depot -M "${PWD}/organizations/peerOrganizations/depot.supplychain.com/peers/peer0.depot.supplychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/depot/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/depot.supplychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/depot.supplychain.com/peers/peer0.depot.supplychain.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-depot -M "${PWD}/organizations/peerOrganizations/depot.supplychain.com/peers/peer0.depot.supplychain.com/tls" --enrollment.profile tls --csr.hosts peer0.depot.supplychain.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/depot/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/depot.supplychain.com/peers/peer0.depot.supplychain.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/depot.supplychain.com/peers/peer0.depot.supplychain.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/depot.supplychain.com/peers/peer0.depot.supplychain.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/depot.supplychain.com/peers/peer0.depot.supplychain.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/depot.supplychain.com/peers/peer0.depot.supplychain.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/depot.supplychain.com/peers/peer0.depot.supplychain.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-depot -M "${PWD}/organizations/peerOrganizations/depot.supplychain.com/users/User1@depot.supplychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/depot/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/depot.supplychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/depot.supplychain.com/users/User1@depot.supplychain.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://depotadmin:depotadminpw@localhost:11054 --caname ca-depot -M "${PWD}/organizations/peerOrganizations/depot.supplychain.com/users/Admin@depot.supplychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/depot/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/depot.supplychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/depot.supplychain.com/users/Admin@depot.supplychain.com/msp/config.yaml"
}

function createHQ() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/HQ.supplychain.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/HQ.supplychain.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:12054 --caname ca-HQ --tls.certfiles "${PWD}/organizations/fabric-ca/HQ/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-12054-ca-HQ.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-12054-ca-HQ.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-12054-ca-HQ.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-12054-ca-HQ.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy HQ's CA cert to HQ's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/HQ/ca-cert.pem" "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/msp/tlscacerts/ca.crt"

  # Copy HQ's CA cert to HQ's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/HQ/ca-cert.pem" "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/tlsca/tlsca.dHQ.supplychain.com-cert.pem"

  # Copy HQ's CA cert to HQ's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/ca"
  cp "${PWD}/organizations/fabric-ca/HQ/ca-cert.pem" "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/ca/ca.HQ.supplychain.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-HQ --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/HQ/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-HQ --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/HQ/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-HQ --id.name HQadmin --id.secret HQadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/HQ/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:12054 --caname ca-HQ -M "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/peers/peer0.HQ.supplychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/HQ/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/peers/peer0.HQ.supplychain.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:12054 --caname ca-HQ -M "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/peers/peer0.HQ.supplychain.com/tls" --enrollment.profile tls --csr.hosts peer0.HQ.supplychain.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/HQ/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/peers/peer0.HQ.supplychain.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/peers/peer0.HQ.supplychain.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/peers/peer0.HQ.supplychain.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/peers/peer0.HQ.supplychain.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/peers/peer0.HQ.supplychain.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/peers/peer0.HQ.supplychain.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:12054 --caname ca-HQ -M "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/users/User1@HQ.supplychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/HQ/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/users/User1@HQ.supplychain.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://HQadmin:HQadminpw@localhost:12054 --caname ca-HQ -M "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/users/Admin@HQ.supplychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/HQ/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/HQ.supplychain.com/users/Admin@HQ.supplychain.com/msp/config.yaml"
}


function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/supplychain.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/supplychain.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/supplychain.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/supplychain.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/supplychain.com/msp/tlscacerts/tlsca.supplychain.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/supplychain.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/supplychain.com/tlsca/tlsca.supplychain.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/supplychain.com/orderers/orderer.supplychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/supplychain.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/supplychain.com/orderers/orderer.supplychain.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/supplychain.com/orderers/orderer.supplychain.com/tls" --enrollment.profile tls --csr.hosts orderer.supplychain.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/supplychain.com/orderers/orderer.supplychain.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/supplychain.com/orderers/orderer.supplychain.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/supplychain.com/orderers/orderer.supplychain.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/supplychain.com/orderers/orderer.supplychain.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/supplychain.com/orderers/orderer.supplychain.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/supplychain.com/orderers/orderer.supplychain.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/supplychain.com/orderers/orderer.supplychain.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/supplychain.com/orderers/orderer.supplychain.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/supplychain.com/orderers/orderer.supplychain.com/msp/tlscacerts/tlsca.supplychain.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/supplychain.com/users/Admin@supplychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/supplychain.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/supplychain.com/users/Admin@supplychain.com/msp/config.yaml"
}

createFactory
createLogistics
createDepot
createHQ
createOrderer
